# Generated by rust2rpm 28
%bcond check 1

%global crate rmpc

Name:           rust-rmpc
Version:        0.11.0
Release:        %autorelease
Summary:        Beautiful and configurable TUI client for MPD

License:        BSD-3-Clause
URL:            https://crates.io/crates/rmpc
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A beautiful and configurable TUI client for MPD.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
License:        BSD 3-Clause
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc CHANGELOG.md
%doc CONTRIBUTING.md
%doc FAQ.md
%doc README.md
%{_bindir}/rmpc

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
